<?xml version="1.0" encoding="utf-8"?><Database Name="Database1" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\Database1.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Database1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.category" Member="categories">
    <Type Name="category">
      <Column Name="categoryid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="categoryname" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="category_item" Member="items" ThisKey="categoryid" OtherKey="categoryid" Type="item" />
    </Type>
  </Table>
  <Table Name="dbo.customer" Member="customers">
    <Type Name="customer">
      <Column Name="customerid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="cnic" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="customer_receipt" Member="receipts" ThisKey="customerid" OtherKey="customerid" Type="receipt" />
    </Type>
  </Table>
  <Table Name="dbo.receipt" Member="receipts">
    <Type Name="receipt">
      <Column Name="receiptid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="customerid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="totalamount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="customer_receipt" Member="customer" ThisKey="customerid" OtherKey="customerid" Type="customer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.item" Member="items">
    <Type Name="item">
      <Column Name="itemid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="itemname" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="itemsize" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="itemprice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="categoryid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="brandname" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="itemimage" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="category_item" Member="category" ThisKey="categoryid" OtherKey="categoryid" Type="category" IsForeignKey="true" />
    </Type>
  </Table>
</Database>